import {
  User,
  Department,
  Cycle,
  MeasurementType,
  Objective,
  KeyResult,
  Measurement,
  ApprovalStep,
  CheckIn,
  ProgressUpdate,
  Comment,
  Attachment,
  Score,
  Notification,
  AuditEntry,
  Template,
  Workflow,
  PerformanceReviewCycle,
  PerformanceEvaluation,
  EvaluationCriteria,
  NotificationPreference,
  MeetingItem,
  FeedMoment,
  TaskItem,
} from '../types';

export const INITIAL_DEMO_DATE = '2026-11-10T12:00:00.000Z';

export const SEED_USERS: User[] = [
  {
    id: 1,
    name: 'Mohammed Ashraf',
    email: 'mohammedashraf@brandcrock.com',
    role: 'EMPLOYEE',
    title: 'Sales Executive',
    departmentId: 1,
    managerId: 2,
    active: true,
    avatar: 'MA',
    employeeCode: 'EMP-1001',
  },
  {
    id: 2,
    name: 'Ravi Menon',
    email: 'ravi.menon@company.com',
    role: 'MANAGER',
    title: 'Sales Team Lead',
    departmentId: 1,
    managerId: 4,
    active: true,
    avatar: 'RM',
    employeeCode: 'MGR-2001',
  },
  {
    id: 3,
    name: 'Priya Nair',
    email: 'priya.nair@company.com',
    role: 'HR_ADMIN',
    title: 'HR Manager',
    departmentId: 4,
    active: true,
    avatar: 'PN',
    employeeCode: 'ADM-3001',
  },
  {
    id: 4,
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@company.com',
    role: 'MANAGER',
    title: 'VP of Engineering',
    departmentId: 2,
    active: true,
    avatar: 'RS',
    employeeCode: 'MGR-2002',
  },
  {
    id: 5,
    name: 'Sneha Rao',
    email: 'sneha.rao@company.com',
    role: 'EMPLOYEE',
    title: 'Senior Software Engineer',
    departmentId: 2,
    managerId: 4,
    active: true,
    avatar: 'SR',
    employeeCode: 'EMP-1002',
  },
  {
    id: 6,
    name: 'Vikram Patel',
    email: 'vikram.patel@company.com',
    role: 'EMPLOYEE',
    title: 'Frontend Engineer',
    departmentId: 2,
    managerId: 4,
    active: true,
    avatar: 'VP',
    employeeCode: 'EMP-1003',
  },
  {
    id: 7,
    name: 'Anita Desai',
    email: 'anita.desai@company.com',
    role: 'MANAGER',
    title: 'Customer Support Lead',
    departmentId: 3,
    active: true,
    avatar: 'AD',
    employeeCode: 'MGR-2003',
  },
  {
    id: 8,
    name: 'Karthik Sundaram',
    email: 'karthik.s@company.com',
    role: 'EMPLOYEE',
    title: 'Customer Success Specialist',
    departmentId: 3,
    managerId: 7,
    active: true,
    avatar: 'KS',
    employeeCode: 'EMP-1004',
  },
  {
    id: 9,
    name: 'Meera Iyer',
    email: 'meera.iyer@company.com',
    role: 'EMPLOYEE',
    title: 'HR Generalist',
    departmentId: 4,
    managerId: 3,
    active: true,
    avatar: 'MI',
    employeeCode: 'EMP-1005',
  },
  {
    id: 10,
    name: 'Santhiya',
    email: 'santhiya@profitokrs.com',
    role: 'MANAGER',
    title: 'Strategy & Growth Lead',
    departmentId: 10,
    active: true,
    avatar: 'S',
    employeeCode: 'EMP-1010',
  },
  {
    id: 11,
    name: 'Aakash D',
    email: 'aakash.d@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Sales Strategy Associate',
    departmentId: 1,
    managerId: 10,
    active: true,
    avatar: 'AD',
    employeeCode: 'EMP-1011',
  },
  {
    id: 12,
    name: 'Boomika K',
    email: 'boomika.k@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Product Growth Specialist',
    departmentId: 2,
    managerId: 10,
    active: true,
    avatar: 'BK',
    employeeCode: 'EMP-1012',
  },
  {
    id: 13,
    name: 'Deepika K',
    email: 'deepika.k@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Frontend Engineer',
    departmentId: 2,
    managerId: 10,
    active: true,
    avatar: 'DK',
    employeeCode: 'EMP-1013',
  },
  {
    id: 14,
    name: 'Deva Dharshini',
    email: 'deva.d@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Operations & Process Lead',
    departmentId: 6,
    managerId: 10,
    active: true,
    avatar: 'DD',
    employeeCode: 'EMP-1014',
  },
  {
    id: 15,
    name: 'Gowri S',
    email: 'gowri.s@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Quality & Test Engineer',
    departmentId: 8,
    managerId: 10,
    active: true,
    avatar: 'GS',
    employeeCode: 'EMP-1015',
  },
  {
    id: 16,
    name: 'Hari Krishnan',
    email: 'hari.k@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Backend Systems Engineer',
    departmentId: 2,
    managerId: 10,
    active: true,
    avatar: 'HK',
    employeeCode: 'EMP-1016',
  },
  {
    id: 17,
    name: 'Kalaiarasi K',
    email: 'kalaiarasi.k@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Marketing Performance Analyst',
    departmentId: 7,
    managerId: 10,
    active: true,
    avatar: 'KK',
    employeeCode: 'EMP-1017',
  },
  {
    id: 18,
    name: 'Praveena Sharin',
    email: 'praveena.s@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'HR People Partner',
    departmentId: 4,
    managerId: 10,
    active: true,
    avatar: 'PS',
    employeeCode: 'EMP-1018',
  },
  {
    id: 19,
    name: 'Raghunath R',
    email: 'raghunath.r@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Customer Success Executive',
    departmentId: 3,
    managerId: 10,
    active: true,
    avatar: 'RR',
    employeeCode: 'EMP-1019',
  },
  {
    id: 20,
    name: 'Shastha Shree',
    email: 'shastha.s@profitokrs.com',
    role: 'EMPLOYEE',
    title: 'Brand & Content Strategist',
    departmentId: 7,
    managerId: 10,
    active: true,
    avatar: 'SS',
    employeeCode: 'EMP-1020',
  },
];

export const SEED_DEPARTMENTS: Department[] = [
  { id: 1, name: 'Sales', description: 'Enterprise and mid-market revenue generation' },
  { id: 2, name: 'Engineering', description: 'Product development and infrastructure' },
  { id: 3, name: 'Customer Service', description: 'Customer happiness and technical support' },
  { id: 4, name: 'Human Resources', description: 'People operations and organizational development' },
  { id: 5, name: 'Corporate', description: 'Executive leadership and company-wide governance' },
  { id: 6, name: 'Manufacturing', description: 'Supply chain, operations and production' },
  { id: 7, name: 'Marketing', description: 'Brand awareness, demand generation and acquisition' },
  { id: 8, name: 'Quality', description: 'Quality assurance, compliance and standards' },
  { id: 9, name: 'Research', description: 'R&D, innovation and technology experimentation' },
  { id: 10, name: 'yoga', description: 'Health & wellness program initiatives and growth' },
];

export const SEED_CYCLES: Cycle[] = [
  {
    id: 1,
    name: 'Q3 2026 OKR Cycle',
    description: 'Q3 Goal tracking',
    startDate: '2026-07-01T00:00:00.000Z',
    endDate: '2026-09-30T23:59:59.000Z',
    status: 'Completed',
    ownerId: 3,
  },
  {
    id: 2,
    name: 'Q4 2026 OKR Cycle',
    description: 'Q4 Strategic objectives and quarterly key results',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    status: 'Active',
    ownerId: 3,
  },
  {
    id: 3,
    name: 'Q1 2027 OKR Cycle',
    description: 'Q1 Planning cycle',
    startDate: '2027-01-01T00:00:00.000Z',
    endDate: '2027-03-31T23:59:59.000Z',
    status: 'Draft',
    ownerId: 3,
  },
];

export const SEED_MEASUREMENT_TYPES: MeasurementType[] = [
  { id: 1, name: 'Number', unitSymbol: '' },
  { id: 2, name: 'Currency', unitSymbol: '₹' },
  { id: 3, name: 'Percentage', unitSymbol: '%' },
];

export const SEED_WORKFLOWS: Workflow[] = [
  {
    id: 1,
    name: 'Standard OKR Approval',
    status: 'ACTIVE',
    stages: [
      { stage: 1, stageName: 'Manager Review', level: 1, approverRole: 'MANAGER' },
      { stage: 2, stageName: 'HR/Admin Review', level: 2, approverRole: 'HR_ADMIN' },
    ],
  },
];

export const SEED_OBJECTIVES: Objective[] = [
  {
    id: 1,
    cycleId: 2,
    ownerId: 3,
    level: 'Organization',
    title: 'Increase revenue 20%',
    description: 'Accelerate company-wide top line revenue growth through enterprise customer acquisition and retention.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 3,
    createdAt: '2026-10-01T09:00:00.000Z',
  },
  {
    id: 2,
    cycleId: 2,
    ownerId: 2,
    level: 'Department',
    departmentId: 1,
    parentObjectiveId: 1,
    title: 'Grow enterprise sales 30%',
    description: 'Target Tier-1 corporate clients across India and APAC region with high-touch sales outreach.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 2,
    createdAt: '2026-10-02T10:00:00.000Z',
  },
  {
    id: 3,
    cycleId: 2,
    ownerId: 2,
    level: 'Team',
    departmentId: 1,
    parentObjectiveId: 2,
    title: 'Close 15 enterprise deals',
    description: 'Sales team execution to sign contracts with enterprise customers above 20L ACV.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 2,
    createdAt: '2026-10-03T11:00:00.000Z',
  },
  {
    id: 4,
    cycleId: 2,
    ownerId: 1, // Ashraf
    level: 'Individual',
    departmentId: 1,
    parentObjectiveId: 3,
    title: 'Close 3 enterprise deals',
    description: 'Prospect, negotiate, and execute 3 high-value enterprise contracts in the banking and logistics sectors.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 50,
    status: 'Draft',
    approvalState: 'NotSubmitted',
    submissionNo: 1,
    createdBy: 1,
    createdAt: '2026-10-05T14:30:00.000Z',
  },
  {
    id: 5,
    cycleId: 2,
    ownerId: 1, // Ashraf
    level: 'Individual',
    departmentId: 1,
    parentObjectiveId: 2,
    title: 'Expand outbound sales outreach',
    description: 'Run targeted B2B executive outbound campaigns to generate fresh pipeline for Q4 and Q1.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 50,
    status: 'Active',
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 1,
    createdAt: '2026-10-04T09:30:00.000Z',
  },
  {
    id: 6,
    cycleId: 2,
    ownerId: 8, // Karthik Sundaram
    level: 'Individual',
    departmentId: 3,
    title: 'Customer onboarding turnaround optimization',
    description: 'Reduce onboarding duration for new enterprise accounts while raising CSAT.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Draft',
    approvalState: 'Returned',
    submissionNo: 1,
    createdBy: 8,
    createdAt: '2026-10-06T11:00:00.000Z',
  },
  {
    id: 7,
    cycleId: 2,
    ownerId: 5, // Sneha Rao
    level: 'Individual',
    departmentId: 2,
    title: 'Core API latency and performance enhancement',
    description: 'Profile slow SQL queries and implement distributed caching to drop p95 latency under 150ms.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Draft',
    approvalState: 'PendingManager',
    submissionNo: 1,
    createdBy: 5,
    createdAt: '2026-10-08T10:15:00.000Z',
  },
  {
    id: 8,
    cycleId: 2,
    ownerId: 6, // Vikram Patel
    level: 'Individual',
    departmentId: 2,
    title: 'Design System component migration and accessibility compliance',
    description: 'Migrate core legacy components to accessible Radix primitives and WCAG 2.1 AA standards.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Draft',
    approvalState: 'PendingHR',
    submissionNo: 1,
    createdBy: 6,
    createdAt: '2026-10-07T12:00:00.000Z',
  },
  {
    id: 9,
    cycleId: 2,
    ownerId: 8, // Karthik Sundaram
    level: 'Individual',
    departmentId: 3,
    title: 'Automate legacy support ticket categorization',
    description: 'Implement automated triage heuristics to direct incoming urgent tickets to specialists.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Draft',
    approvalState: 'Rejected',
    submissionNo: 1,
    createdBy: 8,
    createdAt: '2026-10-09T14:00:00.000Z',
  },
  {
    id: 10,
    cycleId: 2,
    ownerId: 1,
    level: 'Individual',
    departmentId: 1,
    title: 'Q4 Cold calling pilot in northern territory',
    description: 'Discontinued pilot program.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 0,
    status: 'Archived',
    archiveReason: 'Cancelled',
    approvalState: 'NotSubmitted',
    submissionNo: 1,
    createdBy: 1,
    createdAt: '2026-10-01T15:00:00.000Z',
  },
  // Profit.co Objectives (Matching Friends Application Video)
  {
    id: 11,
    cycleId: 2,
    ownerId: 10, // Santhiya
    departmentId: 10, // yoga
    level: 'Department',
    title: 'Improve customer sales',
    description: 'Elevate customer satisfaction and conversion rates across core channels.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 50,
    status: 'Active',
    health: 'On Track',
    progress: 18,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-08T09:00:00.000Z',
    perspective: 'Customer',
    visibility: 'Public',
    priority: 'High',
    tags: ['Customer', 'Growth'],
  },
  {
    id: 12,
    cycleId: 2,
    ownerId: 10, // Santhiya
    departmentId: 10, // yoga
    level: 'Department',
    title: 'Increase Customer Sales up to 80',
    description: 'Expand direct regional wellness sales outreach and customer acquisition.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 50,
    status: 'Draft',
    progress: 0,
    approvalState: 'NotSubmitted',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-08T09:15:00.000Z',
    perspective: 'Financial',
    visibility: 'Public',
    priority: 'High',
    tags: ['Sales'],
  },
  {
    id: 13,
    cycleId: 2,
    ownerId: 2, // Marketing Lead
    departmentId: 7, // Marketing
    level: 'Department',
    title: 'Increase Sales',
    description: 'Integrated multi-channel marketing campaigns driving annual sales and qualified pipeline.',
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 25,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 2,
    createdAt: '2026-10-08T08:00:00.000Z',
    perspective: 'Financial',
    visibility: 'Public',
    priority: 'High',
    tags: ['Annual', 'Marketing'],
  },
  {
    id: 14,
    cycleId: 2,
    ownerId: 2,
    departmentId: 7, // Marketing
    level: 'Department',
    title: 'Marketing',
    description: 'Brand presence and quarterly marketing sprint.',
    startDate: '2026-07-01T00:00:00.000Z',
    endDate: '2026-09-30T23:59:59.000Z',
    weightage: 50,
    status: 'Active',
    progress: 0,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 2,
    createdAt: '2026-09-22T08:00:00.000Z',
    visibility: 'Public',
    priority: 'Medium',
    tags: ['Branding'],
  },
  // --- Company Strategic Hierarchy Across Departments ---
  {
    id: 50,
    cycleId: 2,
    ownerId: 4,
    level: 'Organization',
    departmentId: 2,
    title: 'Platform Scalability, Security & High Availability',
    description: 'Ensure 99.99% system availability and sub-150ms latency across all global microservices.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 42,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 4,
    createdAt: '2026-10-01T08:00:00.000Z',
    perspective: 'Internal Business Processes',
    visibility: 'Public',
    priority: 'High',
  },
  {
    id: 51,
    cycleId: 2,
    ownerId: 4,
    level: 'Department',
    departmentId: 2,
    parentObjectiveId: 50,
    title: 'Core API latency optimization (< 120ms)',
    description: 'Upgrade high-throughput ingestion pipelines and deploy Redis cluster caching.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 50,
    status: 'Active',
    health: 'On Track',
    progress: 48,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 4,
    createdAt: '2026-10-02T09:00:00.000Z',
    perspective: 'Internal Business Processes',
  },
  {
    id: 52,
    cycleId: 2,
    ownerId: 4,
    level: 'Department',
    departmentId: 2,
    parentObjectiveId: 50,
    title: 'Design System & WCAG 2.1 AA Accessibility Standards',
    description: 'Complete unified component migration across all customer-facing touchpoints.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 50,
    status: 'Active',
    health: 'On Track',
    progress: 60,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 4,
    createdAt: '2026-10-02T10:00:00.000Z',
    perspective: 'Internal Business Processes',
  },
  {
    id: 60,
    cycleId: 2,
    ownerId: 7,
    level: 'Organization',
    departmentId: 3,
    title: 'World-Class Customer Retention & Net Promoter Score',
    description: 'Exceed 94% CSAT and reduce customer onboarding friction to drive negative net revenue churn.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 35,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 7,
    createdAt: '2026-10-01T08:30:00.000Z',
    perspective: 'Customer',
    visibility: 'Public',
    priority: 'High',
  },
  {
    id: 61,
    cycleId: 2,
    ownerId: 7,
    level: 'Department',
    departmentId: 3,
    parentObjectiveId: 60,
    title: 'Accelerate Enterprise Onboarding Turnaround (< 48 Hours)',
    description: 'Streamline data migration pipelines and automated account verification checklists.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 38,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 7,
    createdAt: '2026-10-03T09:00:00.000Z',
    perspective: 'Customer',
  },
  {
    id: 70,
    cycleId: 2,
    ownerId: 2,
    level: 'Organization',
    departmentId: 7,
    title: 'Brand Dominance & Multi-Channel Enterprise Acquisition',
    description: 'Establish BrandCrock as premier OKR brand generating 2,500 monthly inbound enterprise MQLs.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 30,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 2,
    createdAt: '2026-10-01T09:00:00.000Z',
    perspective: 'Customer',
    visibility: 'Public',
    priority: 'High',
  },
  {
    id: 71,
    cycleId: 2,
    ownerId: 2,
    level: 'Department',
    departmentId: 7,
    parentObjectiveId: 70,
    title: 'Generate 2,500 Qualified Enterprise Inbound Leads',
    description: 'Multi-touch demand generation and content campaigns across Google Search and LinkedIn.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 32,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 2,
    createdAt: '2026-10-03T11:00:00.000Z',
    perspective: 'Customer',
  },
  {
    id: 80,
    cycleId: 2,
    ownerId: 3,
    level: 'Organization',
    departmentId: 4,
    title: 'High Performance Culture & Continuous OKR Adoption',
    description: 'Foster employee development, 95% weekly check-in compliance, and leadership alignment.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 50,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 3,
    createdAt: '2026-10-01T09:00:00.000Z',
    perspective: 'Learning & Growth',
    visibility: 'Public',
    priority: 'Medium',
  },
  {
    id: 81,
    cycleId: 2,
    ownerId: 3,
    level: 'Department',
    departmentId: 4,
    parentObjectiveId: 80,
    title: 'Continuous Weekly OKR Check-in Discipline Across Teams',
    description: 'Conduct training workshops and track timely weekly progress submissions.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 55,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 3,
    createdAt: '2026-10-04T10:00:00.000Z',
    perspective: 'Learning & Growth',
  },
  // --- Cross-department Aligned Objectives for Employee Ashraf (User 1) ---
  {
    id: 32,
    cycleId: 2,
    ownerId: 1, // Ashraf
    level: 'Individual',
    departmentId: 2, // Aligned to Engineering
    parentObjectiveId: 51,
    title: 'Partner with Engineering on Product-Led Sales Demos',
    description: 'Ensure prospective enterprise clients experience frictionless sandbox trials.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 25,
    status: 'Active',
    health: 'On Track',
    progress: 40,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 1,
    createdAt: '2026-10-06T14:00:00.000Z',
    perspective: 'Internal Business Processes',
    visibility: 'Public',
    priority: 'Medium',
  },
  {
    id: 33,
    cycleId: 2,
    ownerId: 1, // Ashraf
    level: 'Individual',
    departmentId: 7, // Aligned to Marketing
    parentObjectiveId: 71,
    title: 'Collaborate with Marketing on High-Intent Enterprise Case Studies',
    description: 'Deliver 3 customer testimonial success stories to accelerate enterprise deal closing.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 25,
    status: 'Active',
    health: 'On Track',
    progress: 50,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 1,
    createdAt: '2026-10-07T11:00:00.000Z',
    perspective: 'Customer',
    visibility: 'Public',
    priority: 'Medium',
  },
  // --- Team Member Objectives for Manager Santhiya (Matching Video) ---
  {
    id: 41,
    cycleId: 2,
    ownerId: 11, // Aakash D
    level: 'Individual',
    departmentId: 1,
    parentObjectiveId: 2,
    title: 'Tier-1 Enterprise Account Outreach & Deal Progression',
    description: 'Drive high-touch engagement with strategic manufacturing and banking prospects.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 45,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T09:00:00.000Z',
    perspective: 'Financial',
  },
  {
    id: 42,
    cycleId: 2,
    ownerId: 12, // Boomika K
    level: 'Individual',
    departmentId: 2,
    parentObjectiveId: 50,
    title: 'Product Feature Usage Analytics & Adoption Acceleration',
    description: 'Track key workflow completion rates and identify drop-off friction points.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 38,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T09:30:00.000Z',
    perspective: 'Internal Business Processes',
  },
  {
    id: 43,
    cycleId: 2,
    ownerId: 13, // Deepika K
    level: 'Individual',
    departmentId: 2,
    parentObjectiveId: 52,
    title: 'Frontend Component Accessibility & Modern Design Tokens',
    description: 'Refactor modal drawers and form controls to accessible standards.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 65,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T10:00:00.000Z',
    perspective: 'Internal Business Processes',
  },
  {
    id: 44,
    cycleId: 2,
    ownerId: 14, // Deva Dharshini
    level: 'Individual',
    departmentId: 6,
    parentObjectiveId: 60,
    title: 'Streamline Operational Workflows & Fulfillment SLAs',
    description: 'Automate weekly metric reporting and cross-departmental handoffs.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 52,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T11:00:00.000Z',
    perspective: 'Internal Business Processes',
  },
  {
    id: 45,
    cycleId: 2,
    ownerId: 15, // Gowri S
    level: 'Individual',
    departmentId: 8,
    parentObjectiveId: 50,
    title: 'Automated Regression Suite & End-to-End Test Coverage',
    description: 'Increase automated scenario test coverage across core OKR lifecycle workflows.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'At Risk',
    progress: 25,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T12:00:00.000Z',
    perspective: 'Internal Business Processes',
  },
  {
    id: 46,
    cycleId: 2,
    ownerId: 16, // Hari Krishnan
    level: 'Individual',
    departmentId: 2,
    parentObjectiveId: 51,
    title: 'Database Query Optimization & Async Worker Pipeline',
    description: 'Optimize high-traffic SQL read operations and background event listeners.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 44,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T13:00:00.000Z',
    perspective: 'Internal Business Processes',
  },
  {
    id: 47,
    cycleId: 2,
    ownerId: 17, // Kalaiarasi K
    level: 'Individual',
    departmentId: 7,
    parentObjectiveId: 71,
    title: 'Paid Search & Social Demand Generation Campaigns',
    description: 'Optimize campaign spend efficiency to drop cost per lead below target benchmark.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 36,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T14:00:00.000Z',
    perspective: 'Customer',
  },
  {
    id: 48,
    cycleId: 2,
    ownerId: 18, // Praveena Sharin
    level: 'Individual',
    departmentId: 4,
    parentObjectiveId: 81,
    title: 'Employee Onboarding & OKR Training Modules Completion',
    description: 'Ensure 100% of newly onboarded hires complete the Goal Setting Academy training.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'In Trouble',
    progress: 15,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T15:00:00.000Z',
    perspective: 'Learning & Growth',
  },
  {
    id: 49,
    cycleId: 2,
    ownerId: 19, // Raghunath R
    level: 'Individual',
    departmentId: 3,
    parentObjectiveId: 61,
    title: 'Enterprise Support Ticket Resolution P90 Turnaround',
    description: 'Resolve high-priority technical escalations within 4 business hours.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 58,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T16:00:00.000Z',
    perspective: 'Customer',
  },
  {
    id: 500,
    cycleId: 2,
    ownerId: 20, // Shastha Shree
    level: 'Individual',
    departmentId: 7,
    parentObjectiveId: 70,
    title: 'B2B Thought Leadership Whitepapers & Content Series',
    description: 'Publish quarterly research reports on OKR operational methodology and team success.',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    weightage: 100,
    status: 'Active',
    health: 'On Track',
    progress: 40,
    approvalState: 'Approved',
    submissionNo: 1,
    createdBy: 10,
    createdAt: '2026-10-05T17:00:00.000Z',
    perspective: 'Customer',
  },
];

export const SEED_KEY_RESULTS: KeyResult[] = [
  // Under Objective 1 (Increase revenue 20%)
  {
    id: 101,
    objectiveId: 1,
    ownerId: 3,
    name: 'Annual recurring revenue growth to ₹50,00,00,000',
    measurementTypeId: 2,
    direction: 'INCREASE',
    baseline: 400000000,
    target: 500000000,
    current: 445000000,
    achievementPercent: 45.0,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 3,
    createdAt: '2026-10-01T09:30:00.000Z',
  },
  {
    id: 102,
    objectiveId: 1,
    ownerId: 3,
    name: 'Customer net dollar retention rate',
    measurementTypeId: 3,
    direction: 'INCREASE',
    baseline: 85,
    target: 95,
    current: 90,
    achievementPercent: 50.0,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 3,
    createdAt: '2026-10-01T09:30:00.000Z',
  },

  // Under Objective 2 (Grow enterprise sales 30%)
  {
    id: 201,
    objectiveId: 2,
    ownerId: 2,
    name: 'Enterprise sales pipeline generated',
    measurementTypeId: 2,
    direction: 'INCREASE',
    baseline: 50000000,
    target: 150000000,
    current: 98000000,
    achievementPercent: 48.0,
    weightage: 60,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 2,
    createdAt: '2026-10-02T10:30:00.000Z',
  },
  {
    id: 202,
    objectiveId: 2,
    ownerId: 2,
    name: 'Qualified enterprise demo meetings completed',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 20,
    target: 60,
    current: 38,
    achievementPercent: 45.0,
    weightage: 40,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 2,
    createdAt: '2026-10-02T10:30:00.000Z',
  },

  // Under Objective 3 (Close 15 enterprise deals)
  {
    id: 301,
    objectiveId: 3,
    ownerId: 2,
    name: 'Enterprise contracts signed',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 0,
    target: 15,
    current: 7,
    achievementPercent: 46.67,
    weightage: 60,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 2,
    createdAt: '2026-10-03T11:15:00.000Z',
  },
  {
    id: 302,
    objectiveId: 3,
    ownerId: 2,
    name: 'Average enterprise sales cycle days',
    measurementTypeId: 1,
    direction: 'DECREASE',
    baseline: 45,
    target: 30,
    current: 37,
    achievementPercent: 53.33,
    weightage: 40,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 2,
    createdAt: '2026-10-03T11:15:00.000Z',
  },

  // Under Objective 4 (Ashraf's Draft: Close 3 enterprise deals)
  {
    id: 401,
    objectiveId: 4,
    ownerId: 1,
    name: 'Deals closed',
    description: 'Signed agreements with verified payment terms.',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 0,
    target: 3,
    current: 1,
    achievementPercent: 33.33,
    weightage: 60,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'At Risk', // 33.33 vs expected 43.96 -> gap -10.63 -> At Risk
    statusOverridden: false,
    createdBy: 1,
    createdAt: '2026-10-05T14:40:00.000Z',
  },
  {
    id: 402,
    objectiveId: 4,
    ownerId: 1,
    name: 'Deal value closed',
    description: 'Gross contract value in Indian Rupees.',
    measurementTypeId: 2,
    direction: 'INCREASE',
    baseline: 0,
    target: 500000,
    current: 180000,
    achievementPercent: 36.0,
    weightage: 40,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track', // 36.00 vs expected 43.96 -> gap -7.96 -> On Track
    statusOverridden: false,
    createdBy: 1,
    createdAt: '2026-10-05T14:40:00.000Z',
  },

  // Under Objective 5 (Ashraf's Active: Expand outbound sales outreach)
  // Contrast: Objective progress 34.40, expected 43.96 -> Objective is On Track (-9.56) while KR 501 is At Risk!
  {
    id: 501,
    objectiveId: 5,
    ownerId: 1,
    name: 'Outbound prospect executive discovery meetings',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 0,
    target: 20,
    current: 6,
    achievementPercent: 30.0,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'At Risk', // 30.0 vs 43.96 -> gap -13.96 -> At Risk
    statusOverridden: false,
    createdBy: 1,
    createdAt: '2026-10-04T09:45:00.000Z',
  },
  {
    id: 502,
    objectiveId: 5,
    ownerId: 1,
    name: 'Prospect cold email reply rate',
    measurementTypeId: 3,
    direction: 'INCREASE',
    baseline: 4,
    target: 14,
    current: 8,
    achievementPercent: 40.0,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track', // 40.0 vs 43.96 -> gap -3.96 -> On Track
    statusOverridden: false,
    createdBy: 1,
    createdAt: '2026-10-04T09:45:00.000Z',
  },

  // Under Objective 6 (Anita Desai / Karthik - Returned)
  {
    id: 601,
    objectiveId: 6,
    ownerId: 8,
    name: 'Average client onboarding turnaround days',
    measurementTypeId: 1,
    direction: 'DECREASE',
    baseline: 14,
    target: 7,
    current: 11,
    achievementPercent: 42.86,
    weightage: 60,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 8,
    createdAt: '2026-10-06T11:30:00.000Z',
  },
  {
    id: 602,
    objectiveId: 6,
    ownerId: 8,
    name: 'Customer onboarding CSAT rating',
    measurementTypeId: 3,
    direction: 'INCREASE',
    baseline: 70,
    target: 95,
    current: 78,
    achievementPercent: 32.0,
    weightage: 40,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'At Risk',
    statusOverridden: false,
    createdBy: 8,
    createdAt: '2026-10-06T11:30:00.000Z',
  },

  // Under Objective 7 (Sneha Rao - Pending Manager)
  {
    id: 701,
    objectiveId: 7,
    ownerId: 5,
    name: 'p95 API response latency in milliseconds',
    measurementTypeId: 1,
    direction: 'DECREASE',
    baseline: 350,
    target: 150,
    current: 310,
    achievementPercent: 20.0,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'In Trouble', // 20 vs 43.96 -> gap -23.96 / near In Trouble
    statusOverridden: false,
    createdBy: 5,
    createdAt: '2026-10-08T10:30:00.000Z',
  },
  {
    id: 702,
    objectiveId: 7,
    ownerId: 5,
    name: 'Redis cache hit ratio',
    measurementTypeId: 3,
    direction: 'INCREASE',
    baseline: 45,
    target: 90,
    current: 70,
    achievementPercent: 55.56,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 5,
    createdAt: '2026-10-08T10:30:00.000Z',
  },

  // Under Objective 8 (Vikram Patel - Pending HR)
  {
    id: 801,
    objectiveId: 8,
    ownerId: 6,
    name: 'WCAG 2.1 AA compliant UI components verified',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 0,
    target: 25,
    current: 25,
    achievementPercent: 100.0,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'Completed',
    statusOverridden: false,
    createdBy: 6,
    createdAt: '2026-10-07T12:30:00.000Z',
  },
  {
    id: 802,
    objectiveId: 8,
    ownerId: 6,
    name: 'Frontend bundle size reduction percentage',
    measurementTypeId: 3,
    direction: 'INCREASE',
    baseline: 0,
    target: 30,
    current: 12,
    achievementPercent: 40.0,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-11-05T00:00:00.000Z', // Target date already passed! DELAYED
    status: 'At Risk',
    statusOverridden: false,
    createdBy: 6,
    createdAt: '2026-10-07T12:30:00.000Z',
  },
  // Profit.co Key Results (Matching Videos)
  // Under Objective 11 (Improve customer sales - yoga)
  {
    id: 1101,
    objectiveId: 11,
    ownerId: 10, // Santhiya
    name: 'Increase percentage from 30 to 80',
    description: 'Weekly precision KPI check-in with linear projection milestones.',
    measurementTypeId: 3, // Percentage
    direction: 'INCREASE',
    baseline: 30,
    target: 80,
    current: 39,
    achievementPercent: 18.0,
    weightage: 100,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 10,
    createdAt: '2026-10-08T09:30:00.000Z',
    kpiName: 'Accuracy',
    checkInFrequency: 'Every Friday',
    frequencyType: 'Standard',
    visibility: 'Public',
    priority: 'High',
    alignedObjectiveId: 13,
    alignedObjectiveName: 'Increase Sales',
    alignedDepartmentName: 'Marketing',
    contributorIds: [10],
    allowTeamCheckIn: true,
  },
  // Under Objective 12 (Increase Customer Sales up to 80 - Draft)
  {
    id: 1201,
    objectiveId: 12,
    ownerId: 10, // Santhiya
    name: 'Increase Customer Sales up to 80',
    description: 'Direct sales pipeline growth and customer onboarding metrics.',
    measurementTypeId: 1, // Number
    direction: 'INCREASE',
    baseline: 40,
    target: 80,
    current: 40,
    achievementPercent: 0,
    weightage: 100,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 10,
    createdAt: '2026-10-08T09:15:00.000Z',
    kpiName: 'Customer Sales',
    checkInFrequency: 'Every Friday',
    visibility: 'Public',
    priority: 'High',
  },
  // Under Objective 13 (Increase Sales - Marketing)
  {
    id: 1301,
    objectiveId: 13,
    ownerId: 2, // Marketing Lead
    name: 'Increase Accur...',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 0,
    target: 100,
    current: 40,
    achievementPercent: 40.0,
    weightage: 40,
    startDate: '2026-01-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'At Risk',
    statusOverridden: false,
    createdBy: 2,
    createdAt: '2026-10-08T08:15:00.000Z',
    kpiName: 'Accuracy',
    checkInFrequency: 'Every Friday',
    visibility: 'Public',
    priority: 'High',
  },
  {
    id: 1302,
    objectiveId: 13,
    ownerId: 2,
    name: 'Pr2',
    measurementTypeId: 3,
    direction: 'INCREASE',
    baseline: 0,
    target: 100,
    current: 60,
    achievementPercent: 60.0,
    weightage: 30,
    startDate: '2026-01-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 2,
    createdAt: '2026-10-08T08:20:00.000Z',
    checkInFrequency: 'Every Friday',
    visibility: 'Public',
  },
  {
    id: 1303,
    objectiveId: 13,
    ownerId: 2,
    name: 'Pr1',
    measurementTypeId: 3,
    direction: 'INCREASE',
    baseline: 0,
    target: 100,
    current: 0,
    achievementPercent: 0.0,
    weightage: 30,
    startDate: '2026-01-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'In Trouble',
    statusOverridden: false,
    createdBy: 2,
    createdAt: '2026-10-08T08:25:00.000Z',
    checkInFrequency: 'Every Friday',
    visibility: 'Public',
  },
  // Under Objective 51 (Engineering: Core API Latency)
  {
    id: 5101,
    objectiveId: 51,
    ownerId: 4,
    name: 'P95 API request latency under 120ms',
    measurementTypeId: 1,
    direction: 'DECREASE',
    baseline: 240,
    target: 120,
    current: 165,
    achievementPercent: 62.5,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 4,
    createdAt: '2026-10-02T09:30:00.000Z',
    kpiName: 'Latency (ms)',
  },
  {
    id: 5102,
    objectiveId: 51,
    ownerId: 16, // Hari Krishnan
    name: 'Distributed cache hit ratio above 85%',
    measurementTypeId: 3,
    direction: 'INCREASE',
    baseline: 50,
    target: 85,
    current: 78,
    achievementPercent: 80.0,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 16,
    createdAt: '2026-10-05T13:30:00.000Z',
    kpiName: 'Cache Hit %',
  },
  // Under Objective 52 (Engineering: Design System)
  {
    id: 5201,
    objectiveId: 52,
    ownerId: 13, // Deepika K
    name: 'Migrate 40 core UI components to accessible design tokens',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 10,
    target: 40,
    current: 32,
    achievementPercent: 73.3,
    weightage: 60,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 13,
    createdAt: '2026-10-05T10:30:00.000Z',
    kpiName: '# Components',
  },
  // Under Objective 61 (Customer Service: Onboarding Turnaround)
  {
    id: 6101,
    objectiveId: 61,
    ownerId: 19, // Raghunath R
    name: 'Average client onboarding duration under 48 hours',
    measurementTypeId: 1,
    direction: 'DECREASE',
    baseline: 120,
    target: 48,
    current: 72,
    achievementPercent: 66.7,
    weightage: 50,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 19,
    createdAt: '2026-10-05T16:30:00.000Z',
    kpiName: 'Hours',
  },
  // Under Objective 71 (Marketing: 2500 Leads)
  {
    id: 7101,
    objectiveId: 71,
    ownerId: 17, // Kalaiarasi K
    name: 'Generate 2,500 Marketing Qualified Leads (MQLs)',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 500,
    target: 2500,
    current: 1450,
    achievementPercent: 47.5,
    weightage: 60,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 17,
    createdAt: '2026-10-05T14:30:00.000Z',
    kpiName: '# MQLs',
  },
  // Under Objective 32 (Employee Ashraf aligned to Engineering)
  {
    id: 3201,
    objectiveId: 32,
    ownerId: 1, // Ashraf
    name: 'Deliver 12 frictionless enterprise demo sandbox environments',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 0,
    target: 12,
    current: 5,
    achievementPercent: 41.7,
    weightage: 100,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 1,
    createdAt: '2026-10-06T14:30:00.000Z',
    kpiName: '# Demos',
  },
  // Under Objective 33 (Employee Ashraf aligned to Marketing)
  {
    id: 3301,
    objectiveId: 33,
    ownerId: 1, // Ashraf
    name: 'Secure 3 signed customer case study publications',
    measurementTypeId: 1,
    direction: 'INCREASE',
    baseline: 0,
    target: 3,
    current: 2,
    achievementPercent: 66.7,
    weightage: 100,
    startDate: '2026-10-01T00:00:00.000Z',
    targetDate: '2026-12-31T23:59:59.000Z',
    status: 'On Track',
    statusOverridden: false,
    createdBy: 1,
    createdAt: '2026-10-07T11:30:00.000Z',
    kpiName: '# Case Studies',
  },
];

export const SEED_MEASUREMENTS: Measurement[] = [
  // KR 401 Deal closed measurements for forecast
  { id: 1, keyResultId: 401, value: 0, previousValue: 0, progress: 0, measuredAt: '2026-10-01T10:00:00.000Z', recordedBy: 1, comment: 'Baseline verified' },
  { id: 2, keyResultId: 401, value: 0.5, previousValue: 0, progress: 16.67, measuredAt: '2026-10-15T10:00:00.000Z', recordedBy: 1, comment: 'First lead negotiation advanced' },
  { id: 3, keyResultId: 401, value: 0.8, previousValue: 0.5, progress: 26.67, measuredAt: '2026-10-28T10:00:00.000Z', recordedBy: 1, comment: 'Draft contract shared with legal' },
  { id: 4, keyResultId: 401, value: 1.0, previousValue: 0.8, progress: 33.33, measuredAt: '2026-11-04T10:00:00.000Z', recordedBy: 1, comment: 'Enterprise contract signed with Apex Logistics' },

  // KR 402 Deal value closed measurements
  { id: 5, keyResultId: 402, value: 0, previousValue: 0, progress: 0, measuredAt: '2026-10-01T10:00:00.000Z', recordedBy: 1, comment: 'Cycle start' },
  { id: 6, keyResultId: 402, value: 60000, previousValue: 0, progress: 12.0, measuredAt: '2026-10-14T10:00:00.000Z', recordedBy: 1, comment: 'Preliminary PO issued' },
  { id: 7, keyResultId: 402, value: 120000, previousValue: 60000, progress: 24.0, measuredAt: '2026-10-25T10:00:00.000Z', recordedBy: 1, comment: 'Second milestone paid' },
  { id: 8, keyResultId: 402, value: 180000, previousValue: 120000, progress: 36.0, measuredAt: '2026-11-04T10:00:00.000Z', recordedBy: 1, comment: 'Apex deal invoice cleared' },

  // KR 501 Outbound discovery meetings
  { id: 9, keyResultId: 501, value: 0, previousValue: 0, progress: 0, measuredAt: '2026-10-01T09:00:00.000Z', recordedBy: 1, comment: 'Campaign kickoff' },
  { id: 10, keyResultId: 501, value: 2, previousValue: 0, progress: 13.33, measuredAt: '2026-10-12T09:00:00.000Z', recordedBy: 1, comment: '2 CIO meetings completed' },
  { id: 11, keyResultId: 501, value: 4, previousValue: 2, progress: 26.67, measuredAt: '2026-10-24T09:00:00.000Z', recordedBy: 1, comment: '2 VP Tech meetings held' },
  { id: 12, keyResultId: 501, value: 6, previousValue: 4, progress: 40.0, measuredAt: '2026-11-06T09:00:00.000Z', recordedBy: 1, comment: 'Recent session with FinTech head' },
];

export const SEED_APPROVAL_STEPS: ApprovalStep[] = [
  // Objective 7 (Sneha Rao -> Level 1 pending manager Ravi/Rajesh)
  {
    id: 1,
    objectiveId: 7,
    cycleId: 2,
    employeeId: 5,
    stage: 1,
    stageName: 'Manager Review',
    approverId: 4,
    submissionNo: 1,
    status: 'PENDING',
    createdAt: '2026-10-08T10:20:00.000Z',
  },
  // Objective 8 (Vikram Patel -> Level 1 approved, Level 2 pending HR Priya)
  {
    id: 2,
    objectiveId: 8,
    cycleId: 2,
    employeeId: 6,
    stage: 1,
    stageName: 'Manager Review',
    approverId: 4,
    submissionNo: 1,
    status: 'APPROVED',
    comments: 'Strong engineering OKR set. Fully endorsed.',
    decidedAt: '2026-10-08T14:00:00.000Z',
    createdAt: '2026-10-07T12:15:00.000Z',
  },
  {
    id: 3,
    objectiveId: 8,
    cycleId: 2,
    employeeId: 6,
    stage: 2,
    stageName: 'HR/Admin Review',
    approverId: 3,
    submissionNo: 1,
    status: 'PENDING',
    createdAt: '2026-10-08T14:00:00.000Z',
  },
  // Objective 6 (Karthik Sundaram -> Returned by manager Anita)
  {
    id: 4,
    objectiveId: 6,
    cycleId: 2,
    employeeId: 8,
    stage: 1,
    stageName: 'Manager Review',
    approverId: 7,
    submissionNo: 1,
    status: 'RETURNED',
    comments: 'Please split KR 2 into two measurable targets and clarify the customer cohort.',
    decidedAt: '2026-10-07T16:00:00.000Z',
    createdAt: '2026-10-06T11:15:00.000Z',
  },
  // Objective 9 (Karthik Sundaram -> Rejected)
  {
    id: 5,
    objectiveId: 9,
    cycleId: 2,
    employeeId: 8,
    stage: 1,
    stageName: 'Manager Review',
    approverId: 7,
    submissionNo: 1,
    status: 'REJECTED',
    comments: 'Deprioritized for Q4. Team capacity will focus on onboarding.',
    decidedAt: '2026-10-10T11:00:00.000Z',
    createdAt: '2026-10-09T14:15:00.000Z',
  },
];

export const SEED_CHECKINS: CheckIn[] = [
  {
    id: 1,
    objectiveId: 5,
    keyResultId: 501,
    employeeId: 1,
    date: '2026-10-15T10:00:00.000Z',
    status: 'REVIEWED',
    frequencyInterval: 2,
    frequencyUnit: 'WEEK',
    reviewedBy: 2,
    reviewedAt: '2026-10-16T12:00:00.000Z',
    reviewRemarks: 'Great initial traction on enterprise discovery.',
    progressUpdates: [
      {
        id: 1,
        progressValue: 2,
        progressPercentage: 10,
        updateDate: '2026-10-15T10:00:00.000Z',
        remarks: 'Two meetings scheduled with retail firms.',
        submittedBy: 1,
      },
    ],
  },
  {
    id: 2,
    objectiveId: 5,
    keyResultId: 501,
    employeeId: 1,
    date: '2026-10-29T10:00:00.000Z',
    status: 'SUBMITTED',
    frequencyInterval: 2,
    frequencyUnit: 'WEEK',
    progressUpdates: [
      {
        id: 2,
        progressValue: 4,
        progressPercentage: 20,
        updateDate: '2026-10-29T10:00:00.000Z',
        remarks: 'Two more VP Tech meetings held.',
        submittedBy: 1,
      },
    ],
  },
  // Profit.co Check-in (Matching Video 3: 9 Oct 2026, Plan: 38, Actual: 39, On Track)
  {
    id: 101,
    objectiveId: 11,
    keyResultId: 1101,
    employeeId: 10, // Santhiya
    authorName: 'Santhiya',
    date: '2026-10-09T00:00:00.000Z',
    status: 'SUBMITTED',
    frequencyInterval: 1,
    frequencyUnit: 'WEEK',
    planValue: 38,
    actualValue: 39,
    deltaValue: 1,
    deltaPercentage: 2.6,
    calculatedHealth: 'On Track',
    statusBannerText: 'Status set to On Track: actual 39 is above the plan of 38 for this date (2.6%). You can override this if needed.',
    remarks: 'Stage updated from "Not Started" to "In Progress" with the Health "On Track"',
    stageChangeText: 'Stage updated from "Not Started" to "In Progress" with the Health "On Track"',
    progressUpdates: [
      {
        id: 101,
        progressValue: 39,
        progressPercentage: 18,
        updateDate: '2026-10-08T11:36:00.000Z',
        remarks: 'Stage updated from "Not Started" to "In Progress" with the Health "On Track"',
        submittedBy: 10,
      },
    ],
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: 1,
    objectType: 'OBJECTIVE',
    objectId: 4,
    authorId: 1,
    text: 'Drafted Q4 enterprise deals goals in line with sales departmental quota.',
    visibility: 'PUBLIC',
    createdAt: '2026-10-05T15:00:00.000Z',
  },
  {
    id: 2,
    objectType: 'OBJECTIVE',
    objectId: 6,
    authorId: 7,
    text: 'Returned for adjustments to target baseline numbers.',
    visibility: 'PUBLIC',
    createdAt: '2026-10-07T16:05:00.000Z',
  },
  {
    id: 3,
    objectType: 'KEY_RESULT',
    objectId: 401,
    authorId: 2,
    text: 'Keep focus on banking accounts with faster Q4 procurement cycles.',
    visibility: 'CONFIDENTIAL',
    createdAt: '2026-10-10T11:00:00.000Z',
  },
];

export const SEED_ATTACHMENTS: Attachment[] = [
  {
    id: 1,
    objectType: 'OBJECTIVE',
    objectId: 4,
    uploadedBy: 1,
    fileName: 'Apex_Logistics_Executive_Proposal.pdf',
    fileType: 'application/pdf',
    fileSize: 1845000,
    createdAt: '2026-10-20T14:00:00.000Z',
  },
];

export const SEED_SCORES: Score[] = [
  // Cycle 1 (Q3 Completed) - Official FINAL scores
  {
    id: 1,
    cycleId: 1,
    objectiveId: 1,
    ownerId: 1,
    rawAchievementPercent: 92.5,
    calculatedScore: 92.5,
    scoreType: 'FINAL',
    createdAt: '2026-10-02T10:00:00.000Z',
    recordedBy: 3,
  },
  {
    id: 2,
    cycleId: 1,
    objectiveId: 2,
    ownerId: 2,
    rawAchievementPercent: 88.0,
    calculatedScore: 88.0,
    scoreType: 'FINAL',
    createdAt: '2026-10-02T10:30:00.000Z',
    recordedBy: 3,
  },
  {
    id: 3,
    cycleId: 1,
    objectiveId: 3,
    ownerId: 3,
    rawAchievementPercent: 95.0,
    calculatedScore: 95.0,
    scoreType: 'FINAL',
    createdAt: '2026-10-02T11:00:00.000Z',
    recordedBy: 3,
  },
  {
    id: 4,
    cycleId: 1,
    objectiveId: 4,
    ownerId: 4,
    rawAchievementPercent: 91.5,
    calculatedScore: 91.5,
    scoreType: 'FINAL',
    createdAt: '2026-10-02T11:30:00.000Z',
    recordedBy: 3,
  },
  // Cycle 2 (Q4 Active) - Dynamic CALCULATED and certified FINAL scores
  {
    id: 5,
    cycleId: 2,
    objectiveId: 5,
    ownerId: 1,
    rawAchievementPercent: 35.0,
    calculatedScore: 35.0,
    scoreType: 'CALCULATED',
    createdAt: '2026-11-06T12:00:00.000Z',
  },
  {
    id: 6,
    cycleId: 2,
    objectiveId: 6,
    ownerId: 2,
    rawAchievementPercent: 48.0,
    calculatedScore: 48.0,
    scoreType: 'CALCULATED',
    createdAt: '2026-11-07T09:00:00.000Z',
  },
  {
    id: 7,
    cycleId: 2,
    objectiveId: 7,
    ownerId: 4,
    rawAchievementPercent: 62.0,
    calculatedScore: 62.0,
    scoreType: 'CALCULATED',
    createdAt: '2026-11-07T14:30:00.000Z',
  },
  {
    id: 8,
    cycleId: 2,
    objectiveId: 8,
    ownerId: 5,
    rawAchievementPercent: 78.0,
    calculatedScore: 78.0,
    scoreType: 'FINAL',
    createdAt: '2026-11-08T16:00:00.000Z',
    recordedBy: 3,
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    employeeId: 1,
    type: 'OBJECTIVE_APPROVED',
    title: 'Objective Active',
    message: 'Your objective "Expand outbound sales outreach" has been approved by HR.',
    objectType: 'OBJECTIVE',
    objectId: 5,
    read: true,
    createdAt: '2026-10-05T16:00:00.000Z',
  },
  {
    id: 2,
    employeeId: 1,
    type: 'KR_AT_RISK',
    title: 'KR Pace Warning',
    message: 'Key Result "Deals closed" is falling behind expected pace (-10.6 points).',
    objectType: 'KEY_RESULT',
    objectId: 401,
    read: false,
    createdAt: '2026-11-08T09:00:00.000Z',
  },
  {
    id: 3,
    employeeId: 2,
    type: 'APPROVAL_REQUEST',
    title: 'New OKR Submitted for Review',
    message: 'Sneha Rao submitted "Core API latency and performance enhancement" for review.',
    objectType: 'APPROVAL',
    objectId: 1,
    read: false,
    createdAt: '2026-10-08T10:20:00.000Z',
  },
  {
    id: 4,
    employeeId: 3,
    type: 'APPROVAL_REQUEST',
    title: 'Level 2 HR Approval Needed',
    message: 'Vikram Patel\'s objective is waiting for Level 2 HR/Admin approval.',
    objectType: 'APPROVAL',
    objectId: 3,
    read: false,
    createdAt: '2026-10-08T14:05:00.000Z',
  },
];

export const SEED_AUDIT_LOG: AuditEntry[] = [
  {
    id: 1,
    table: 'Objectives',
    recordId: 4,
    action: 'CREATE',
    actionBy: 1,
    actionAt: '2026-10-05T14:30:00.000Z',
    remarks: 'Created draft objective "Close 3 enterprise deals"',
  },
  {
    id: 2,
    table: 'Objectives',
    recordId: 5,
    action: 'APPROVE',
    actionBy: 3,
    actionAt: '2026-10-05T16:00:00.000Z',
    remarks: 'Level 2 HR approval completed',
  },
  {
    id: 3,
    table: 'KeyResults',
    recordId: 401,
    action: 'UPDATE',
    actionBy: 1,
    actionAt: '2026-11-04T10:00:00.000Z',
    remarks: 'Recorded progress update value from 0.8 to 1.0',
    details: [{ column: 'current', oldValue: 0.8, newValue: 1.0 }],
  },
];

export const SEED_TEMPLATES: Template[] = [
  {
    id: 1,
    name: 'Sales Quarterly OKR Template v1',
    version: 1,
    status: 'ACTIVE',
    description: 'Standard quarterly template for Enterprise Account Executives and Sales Leads.',
    objectives: [
      {
        title: 'Exceed quarterly revenue and pipeline targets',
        description: 'Drive high-volume enterprise outreach and close designated ACV commitments.',
        level: 'Individual',
        displayOrder: 1,
        keyResults: [
          {
            name: 'Total booked contract value',
            measurementTypeId: 2,
            direction: 'INCREASE',
            baseline: 0,
            target: 1000000,
            weightage: 60,
          },
          {
            name: 'New enterprise pipeline qualified',
            measurementTypeId: 2,
            direction: 'INCREASE',
            baseline: 0,
            target: 2500000,
            weightage: 40,
          },
        ],
      },
    ],
    assignments: [
      { type: 'DEPARTMENT', targetId: 1 },
      { type: 'ROLE', targetId: 'EMPLOYEE' },
    ],
  },
];

export const SEED_REVIEW_CYCLES: PerformanceReviewCycle[] = [
  {
    id: 1,
    name: 'FY2026 Annual Performance Review',
    cycleId: 2,
    status: 'Active',
    startDate: '2026-11-01T00:00:00.000Z',
    endDate: '2026-12-15T23:59:59.000Z',
  },
];

export const SEED_CRITERIA: EvaluationCriteria[] = [
  { id: 1, name: 'Goal Achievement & Impact', description: 'Degree of OKR completion, business velocity, and contribution to company objectives.', weightage: 40 },
  { id: 2, name: 'Execution Excellence & Quality', description: 'Technical rigor, attention to detail, reliability, and timeliness of deliverables.', weightage: 30 },
  { id: 3, name: 'Collaboration & Values', description: 'Cross-functional alignment, proactive communication, mentorship, and team leadership.', weightage: 30 },
];

export const SEED_EVALUATIONS: PerformanceEvaluation[] = [
  {
    id: 1,
    reviewCycleId: 1,
    employeeId: 1,
    evaluatorId: 1,
    evalType: 'SELF',
    status: 'SUBMITTED',
    overallScore: 88,
    overallRating: 4.4,
    submittedAt: '2026-11-05T15:30:00.000Z',
    comments: 'Strong momentum on enterprise deals in Q4 with healthy pipeline building.',
    responses: [
      { criteriaId: 1, criteriaName: 'Goal Achievement & Impact', responseText: 'Closed Apex Logistics early in the cycle and currently advancing two financial sector prospects.', score: 85, rating: 4.2 },
      { criteriaId: 2, criteriaName: 'Execution Excellence & Quality', responseText: 'Maintained disciplined deal qualification and prompt proposal submissions.', score: 90, rating: 4.5 },
      { criteriaId: 3, criteriaName: 'Collaboration & Values', responseText: 'Partnered closely with Solutions Engineering to speed up technical demonstrations.', score: 90, rating: 4.5 },
    ],
  },
  {
    id: 2,
    reviewCycleId: 1,
    employeeId: 1,
    evaluatorId: 2,
    evalType: 'MANAGER',
    status: 'DRAFT',
    responses: [
      { criteriaId: 1, criteriaName: 'Goal Achievement & Impact', responseText: 'Good progress on key accounts; need to accelerate secondary deals.', score: 82, rating: 4.0 },
      { criteriaId: 2, criteriaName: 'Execution Excellence & Quality', responseText: 'Proposals are well-structured and client feedback is positive.', score: 88, rating: 4.4 },
      { criteriaId: 3, criteriaName: 'Collaboration & Values', responseText: 'Proactive team player in weekly pipeline reviews.', score: 85, rating: 4.2 },
    ],
  },
];

export const SEED_PREFERENCES: NotificationPreference[] = [
  { employeeId: 1, notificationType: 'OBJECTIVE_SUBMITTED', label: 'Objective submission updates', emailEnabled: true, inAppEnabled: true },
  { employeeId: 1, notificationType: 'APPROVAL_DECIDED', label: 'Approval or return decisions', emailEnabled: true, inAppEnabled: true },
  { employeeId: 1, notificationType: 'KR_PACE_WARNING', label: 'KR at-risk pace alerts', emailEnabled: true, inAppEnabled: true },
  { employeeId: 1, notificationType: 'CHECK_IN_REMINDER', label: 'Check-in due reminders', emailEnabled: true, inAppEnabled: true },
  { employeeId: 1, notificationType: 'COMMENT_ADDED', label: 'New comments on your goals', emailEnabled: false, inAppEnabled: true },
];

export const SEED_MEETINGS: MeetingItem[] = [
  {
    id: 1,
    title: 'Weekly OKR Check-in & Team Alignment',
    type: 'OKR Review',
    date: '2026-10-12',
    time: '10:00 AM - 10:45 AM',
    durationMinutes: 45,
    organizerId: 10,
    attendeeIds: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    meetingLink: 'https://meet.brandcrock.com/okr-team-sync',
    notes: 'Review Q4 pace gaps, weekly check-in blockers, and alignment dependencies.',
  },
  {
    id: 2,
    title: '1-on-1 Performance Check-in: Aakash D',
    type: '1-on-1',
    date: '2026-10-13',
    time: '02:00 PM - 02:30 PM',
    durationMinutes: 30,
    organizerId: 10,
    attendeeIds: [10, 11],
    meetingLink: 'https://meet.brandcrock.com/1on1-aakash',
    notes: 'Sales strategy pacing and enterprise pipeline expansion.',
  },
  {
    id: 3,
    title: '1-on-1 OKR Review: Deepika K',
    type: '1-on-1',
    date: '2026-10-14',
    time: '11:30 AM - 12:00 PM',
    durationMinutes: 30,
    organizerId: 10,
    attendeeIds: [10, 13],
    meetingLink: 'https://meet.brandcrock.com/1on1-deepika',
    notes: 'Design System component delivery, WCAG AA compliance, and QA milestones.',
  },
  {
    id: 4,
    title: 'Sales Pacing & Outbound Sync: Mohammed Ashraf',
    type: '1-on-1',
    date: '2026-10-15',
    time: '03:00 PM - 03:30 PM',
    durationMinutes: 30,
    organizerId: 2,
    attendeeIds: [2, 1],
    meetingLink: 'https://meet.brandcrock.com/1on1-ashraf',
    notes: 'Review Apex Logistics contract closing and outbound target pacing.',
  },
];

export const SEED_FEEDS: FeedMoment[] = [
  {
    id: 1,
    authorId: 10,
    type: 'Announcement',
    title: 'Applause for exceptional efforts!',
    content: 'Huge applause to the entire team for achieving 92% on-time check-in discipline this cycle! Keep up the tremendous momentum towards our Q4 strategic targets.',
    badge: 'Corporate',
    likes: 18,
    likedByCurrentUser: true,
    commentsCount: 6,
    createdAt: '2026-10-08T09:30:00.000Z',
  },
  {
    id: 2,
    authorId: 10,
    type: 'Recognition',
    title: 'Outstanding Delivery & Quality',
    content: 'Proud to recognize Deepika K for migrating 32 Design System components ahead of schedule with zero accessibility regressions! Fantastic dedication!',
    badge: 'Excellence',
    targetUserId: 13,
    likes: 24,
    likedByCurrentUser: false,
    commentsCount: 9,
    createdAt: '2026-10-07T14:20:00.000Z',
  },
  {
    id: 3,
    authorId: 2,
    type: 'Recognition',
    title: 'Enterprise Milestone Achieved!',
    content: 'Congratulations to Mohammed Ashraf for signing the enterprise contract with Apex Logistics! Superb execution on enterprise deal progression.',
    badge: 'Superstar',
    targetUserId: 1,
    likes: 21,
    likedByCurrentUser: true,
    commentsCount: 8,
    createdAt: '2026-10-06T16:00:00.000Z',
  },
];

export const SEED_TASKS: TaskItem[] = [
  {
    id: 1,
    title: 'Submit weekly Key Result check-in for Q4 targets',
    assignedToId: 1,
    status: 'Completed',
    dueDate: '2026-10-09',
    priority: 'High',
  },
  {
    id: 2,
    title: 'Prepare enterprise client presentation for Apex Logistics',
    assignedToId: 1,
    status: 'In Progress',
    dueDate: '2026-10-12',
    priority: 'High',
  },
  {
    id: 3,
    title: 'Review 3 check-ins pending manager approval',
    assignedToId: 10,
    status: 'Open',
    dueDate: '2026-10-10',
    priority: 'High',
  },
  {
    id: 4,
    title: 'Finalize Design System component documentation',
    assignedToId: 13,
    status: 'Open',
    dueDate: '2026-10-14',
    priority: 'Medium',
  },
  {
    id: 5,
    title: 'Complete automated regression suite test run',
    assignedToId: 15,
    status: 'Completed',
    dueDate: '2026-10-08',
    priority: 'High',
  },
  {
    id: 6,
    title: 'Run B2B outbound campaign analytics check',
    assignedToId: 17,
    status: 'Open',
    dueDate: '2026-10-15',
    priority: 'Low',
  },
  {
    id: 7,
    title: 'Coordinate quarterly employee engagement survey',
    assignedToId: 18,
    status: 'Open',
    dueDate: '2026-10-16',
    priority: 'Medium',
  },
];

export interface CheckInDisciplineRecord {
  userId: number;
  userName: string;
  avatar: string;
  title: string;
  onTime: number;
  late: number;
  missed: number;
  paused: number;
}

export const SEED_DISCIPLINE: CheckInDisciplineRecord[] = [
  { userId: 11, userName: 'Aakash D', avatar: 'AD', title: 'Sales Strategy Associate', onTime: 1, late: 0, missed: 0, paused: 0 },
  { userId: 12, userName: 'Boomika K', avatar: 'BK', title: 'Product Growth Specialist', onTime: 1, late: 0, missed: 0, paused: 0 },
  { userId: 13, userName: 'Deepika K', avatar: 'DK', title: 'Frontend Engineer', onTime: 1, late: 0, missed: 0, paused: 0 },
  { userId: 14, userName: 'Deva Dharshini', avatar: 'DD', title: 'Operations & Process Lead', onTime: 1, late: 0, missed: 0, paused: 0 },
  { userId: 15, userName: 'Gowri S', avatar: 'GS', title: 'Quality & Test Engineer', onTime: 0, late: 1, missed: 0, paused: 0 },
  { userId: 16, userName: 'Hari Krishnan', avatar: 'HK', title: 'Backend Systems Engineer', onTime: 1, late: 0, missed: 0, paused: 0 },
  { userId: 17, userName: 'Kalaiarasi K', avatar: 'KK', title: 'Marketing Performance Analyst', onTime: 1, late: 0, missed: 0, paused: 0 },
  { userId: 18, userName: 'Praveena Sharin', avatar: 'PS', title: 'HR People Partner', onTime: 0, late: 0, missed: 1, paused: 0 },
  { userId: 19, userName: 'Raghunath R', avatar: 'RR', title: 'Customer Success Executive', onTime: 1, late: 0, missed: 0, paused: 0 },
  { userId: 20, userName: 'Shastha Shree', avatar: 'SS', title: 'Brand & Content Strategist', onTime: 0, late: 0, missed: 0, paused: 1 },
];

